Algoritmo "exercicio02"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Escreva um algoritmo para ler um valor
//  (do teclado) e escrever (na tela) o seu sucessor.
// Autor(a)    : Renan Vitor Rezolino dos Santos
// Data atual  : 23/09/2026
Var
// Seção de Declarações das variáveis 
sucessor,numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(numero)
sucessor <- numero + 1
escreval("O número ",numero," sucessor é ", sucessor)

Fimalgoritmo