Algoritmo "exercicio10"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Ler um valor e escrever a mensagem É MAIOR QUE 10! se o
//valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!
// Autor(a)    : Renan Vitor Rezolino dos Santos
// Data atual  : 23/09/2026
// Declaração das variáveis
Var
// Seção de Declarações das variáveis 
numero:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(numero)

se numero> 10 entao
 escreval(numero, " É maior que 10")
senao
 escreval(numero, " É menor que 10")
fimse


Fimalgoritmo