Algoritmo "exercicio22"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Faça um algoritmo para ler: quantidade atual em estoque,
//quantidade máxima em estoque e quantidade mínima em estoque de um produto.
//Calcular e escrever a quantidade média ((quantidade média = quantidade
//máxima + quantidade mínima)/2). Se a quantidade em estoque for maior ou
//igual a quantidade média escrever a mensagem 'Não efetuar compra', senão
//escrever a mensagem 'Efetuar compra'.
// Autor(a)    : Renan Vitor Rezolino dos Santos
// Data atual  : 26/09/2026
Var
// Seção de Declarações das variáveis 
quantidadeAtual, quantidadeMaxima, quantidadeMinima, quantidadeMedia: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a quantidade atual em estoque: ")
   leia(quantidadeAtual)

   escreva("Digite a quantidade máxima em estoque: ")
   leia(quantidadeMaxima)

   escreva("Digite a quantidade mínima em estoque: ")
   leia(quantidadeMinima)

   quantidadeMedia <- (quantidadeMaxima + quantidadeMinima) / 2

   escreval("Quantidade atual: ", quantidadeAtual)
   escreval("Quantidade máxima: ", quantidadeMaxima)
   escreval("Quantidade mínima: ", quantidadeMinima)
   escreval("Quantidade média: ", quantidadeMedia)

   se quantidadeAtual >= quantidadeMedia entao
      escreval("Não efetuar compra.")
      escreval("O estoque está dentro da quantidade adequada.")
   senao
      escreval("Efetuar compra.")
      escreval("A quantidade em estoque está abaixo da média.")
   fimse
Fimalgoritmo