Algoritmo "L05A"
// Disciplina   :[Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Renan Vitor Rezolino dos Santos
// Data atual  : 24/09/2026
Var
// Seção de Declarações das variáveis 
  numero, quadrado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para numero de 15 ate 200 faca

      quadrado <- numero * numero

      escreval("Quadrado de ", numero, " = ", quadrado)

   fimpara


Fimalgoritmo