Algoritmo "L05E"
// Disciplina   :[Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar todos os valores numéricos inteiros ímpares situados
// na faixa de 0 a 20. Para verificar
// se o número é ímpar, efetuar dentro da malha a verificação lógica desta
// condição com a instrução SE
//perguntando se o número é ímpar; sendo, mostre-o; não sendo, passe para o
//próximo passo.
// Autor(a)    : Renan Vitor Rezolino dos Santos
// Data atual  : 24/09/2026
Var
// Seção de Declarações das variáveis 
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    para numero de 0 ate 20 faca

      se numero % 2 <> 0 entao
         escreval(numero)
      fimse

   fimpara

Fimalgoritmo